// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPersonelSeasonalPaid.Persistence;

#nullable disable

namespace WebPersonelSeasonalPaid.Persistence.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20231213110452_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPersonelSeasonalPaid.Domain.Personel", b =>
                {
                    b.Property<Guid>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("WebPersonelSeasonalPaid.Domain.PersonelSeason", b =>
                {
                    b.Property<Guid>("PersonelSeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Prim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonelSeasonId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PersonelSeasons");
                });

            modelBuilder.Entity("WebPersonelSeasonalPaid.Domain.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SeasonEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SeasonStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("WebPersonelSeasonalPaid.Domain.PersonelSeason", b =>
                {
                    b.HasOne("WebPersonelSeasonalPaid.Domain.Personel", "Personel")
                        .WithMany("ExistingSeason")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebPersonelSeasonalPaid.Domain.Season", "Season")
                        .WithMany("SeasonPersonel")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("WebPersonelSeasonalPaid.Domain.Personel", b =>
                {
                    b.Navigation("ExistingSeason");
                });

            modelBuilder.Entity("WebPersonelSeasonalPaid.Domain.Season", b =>
                {
                    b.Navigation("SeasonPersonel");
                });
#pragma warning restore 612, 618
        }
    }
}
